SETTINGS = [

    ( "CL{MYY}_FUT_CME",                "FGHJKMNQUVXZ",     True     ),
    ( "LO{MYY} {T}{S}.FUT_OPT.NYMEX",   "FGHJKMNQUVXZ",     True     ),
    ( "LO1{MYY} {T}{S}.FUT_OPT.NYMEX",  "FGHJKMNQUVXZ",     True     ),
    ( "LO2{MYY} {T}{S}.FUT_OPT.NYMEX",  "FGHJKMNQUVXZ",     True     ),
    ( "LO3{MYY} {T}{S}.FUT_OPT.NYMEX",  "FGHJKMNQUVXZ",     True     ),
    ( "LO4{MYY} {T}{S}.FUT_OPT.NYMEX",  "FGHJKMNQUVXZ",     True     ),
    ( "RB{MYY}_FUT_CME",                "FGHJKMNQUVXZ",     True     ),
    ( "HO{MYY}_FUT_CME",                "FGHJKMNQUVXZ",     True     ),
    ( "NG{MYY}_FUT_CME",                "FGHJKMNQUVXZ",     True     ),
    ( "LNE{MYY} {T}{S}.FUT_OPT.NYMEX",  "FGHJKMNQUVXZ",     True     ),
    ( "ZC{MYY}_FUT_CME",                "HKNUZ",            True     ),
    ( "OCD{MYY} {T}{S}.FUT_OPT.CBOT",   "FGHJKMNQUVXZ",     True     ),  # short-dated new crop
    ( "OZC{MYY} {T}{S}.FUT_OPT.CBOT",   "FGHJKMNQUVXZ",     True     ),  # american
    ( "ZR{MYY}_FUT_CME",                "FHKNUX",           True     ),
    ( "ZS{MYY}_FUT_CME",                "FHNQUX",           True     ),
    ( "OSD{MYY} {T}{S}.FUT_OPT.CBOT",   "FGHJKMNQUVXZ",     True     ), # short-dated new crop
    ( "OZS{MYY} {T}{S}.FUT_OPT.CBOT",   "FGHJKMNQUVXZ",     True     ), # american
    ( "ZM{MYY}_FUT_CME",                "FHKNQUVZ",         True     ),
    ( "ZL{MYY}_FUT_CME",                "FHKNQUVZ",         True     ),
    ( "ZW{MYY}_FUT_CME",                "HKNUZ",            True     ),
    ( "OZW{MYY} {T}{S}.FUT_OPT.CBOT",   "FGHJKMNQUVXZ",     True     ),
    ( "KE{MYY}_FUT_CME",                "HKNUZ",            True     ),
    ( "ZO{MYY}_FUT_CME",                "HKNUZ",            True     ),
    ( "HE{MYY}_FUT_CME",                "GJKMNQVZ",         True     ),
    ( "HE{MYY} {T}{S}.FUT_OPT.CME",     "GJKMNQVZ",         True     ),
    ( "LE{MYY}_FUT_CME",                "GJMQVZ",           True     ),
    ( "LE{MYY} {T}{S}.FUT_OPT.CME",     "GJMQVZ",           False    ),
    ( "GF{MYY}_FUT_CME",                "FHJKQUVX",         True     ),
    ( "GC{MYY}_FUT_CME",                "GJMQZ",            True     ),
    ( "SI{MYY}_FUT_CME",                "HKNUZ",            True     ),
    ( "HG{MYY}_FUT_CME",                "HKNUZ",            True     ),
    ( "VX{MYY}_FUT_CFE",                "FGHJKMNQUVXZ",     True     ),
    ( "ES{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "NQ{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "YM{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "RTY{MYY}_FUT_CME",               "HMUZ",             True     ),
    ( "ZB{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "ZN{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "ZF{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "ZT{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "SR1{MYY}_FUT_CME",               "HMUZ",             True     ),
    ( "SR3{MYY}_FUT_CME",               "HMUZ",             True     ),
    ( "6E{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "6B{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "6J{MYY}_FUT_CME",                "HMUZ",             True     ),
    ( "6M{MYY}_FUT_CME",                "HMUZ",             True     )
]