python research/sweeps/gen.py ESM24_FUT_CME 5
python research/sweeps/gen.py ESU24_FUT_CME 5
python research/sweeps/gen.py ESZ24_FUT_CME 5
python research/sweeps/gen.py NQM24_FUT_CME 8
python research/sweeps/gen.py NQU24_FUT_CME 8
python research/sweeps/gen.py NQZ24_FUT_CME 8
python research/sweeps/gen.py HOK24_FUT_CME 20
python research/sweeps/gen.py HOM24_FUT_CME 20
python research/sweeps/gen.py RBK24_FUT_CME 20
python research/sweeps/gen.py RBM24_FUT_CME 20
