python research/sweeps/gen.py ESU24_FUT_CME 5
python research/sweeps/gen.py ESZ24_FUT_CME 5
python research/sweeps/gen.py NQU24_FUT_CME 8
python research/sweeps/gen.py NQZ24_FUT_CME 8
python research/sweeps/gen.py HON24_FUT_CME 20
python research/sweeps/gen.py HOQ24_FUT_CME 20
python research/sweeps/gen.py RBN24_FUT_CME 20
python research/sweeps/gen.py RBQ24_FUT_CME 20
python research/sweeps/gen.py CLN24_FUT_CME 5
python research/sweeps/gen.py CLQ24_FUT_CME 5
